server:
  port: 9094
#spring:
#  kafka:
#    bootstrap-servers: 192.168.60.128:9092
#    consumer:
#      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
#      auto-commit-interval: 1
#      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
#      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
#      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
#      auto-offset-reset: earliest
#      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
#      enable-auto-commit: false
#      # 键的反序列化方式
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      # 值的反序列化方式
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: group6
#      topic: myTopic2
#      max-poll-records: 1000 # 作用与批量
#    listener:
#      # 在侦听器容器中运行的线程数。
#      concurrency: 5
#      #listner负责ack，每调用一次，就立即commit
#      ack-mode: manual_immediate
#      missing-topics-fatal: false
#      type: batch

# kafka配置信息
kafka:
  bootstrap-servers: 192.168.60.128:9092
  session-timeout: 50000
  auto-offset-reset: earliest
  enable-auto-commit: false
  auto-commit-interval: 5000
  max-poll-records: 1000
  concurrency: 3
  max-poll-interval: 15000
  max-partition-fetch-bytes: 15728640
  group-id: MY_GROUP
  heartbeat-interval: 3000
  listener:
    ack-mode: MANUAL_IMMEDIATE
    enable-batch: true
  topic:
    pattern: HELLO_TOPIC
