logging:
  config: classpath:logback.xml
kafka:
  bootstrap-server: 192.168.53.26:9092,192.168.53.27:9092,192.168.53.28:9092
  catch:
    url: http://192.168.53.32:8065/codis/
  error:
    url: http://192.168.53.33:9002/email/sendEmail
  errorEmail:
    addName: SDK for kafka
    reToEmail: 19926468792@163.com
    subject: failed to send Email
  producer:
    batch-size: 16785
    buffer-memory: 33554432
    linger: 50
    retries: 3
server:
  port: 8082
