logging:
  config: classpath:logback.xml
kafka:
  bootstrap-server: 10.34.53.31:9092,10.34.53.32:9092,10.34.53.33:9092
  catch:
    url: http://123.126.41.204:20437/codis/
  error:
    url: http://10.34.53.31:9002/email/sendEmail
  errorEmail:
    addName: SDK for kafka
    reToEmail: 19926468792@163.com
    subject: failed to send Email
  producer:
    batch-size: 16785
    buffer-memory: 33554432
    linger: 50
    retries: 3
server:
  port: 8082
