#logging:
#  config: classpath:logback.xml
kafka:
  bootstrap-server: hw_kafka1:19092,hw_kafka2:29092,hw_kafka3:39092
  catch:
    url: http://10.43.50.11:8081/codis/
  consumer:
    auto-commit-interval: 100
    enable-auto-commit: true
    max-poll-records: 8
    session-timeout: 20000
  error:
    url: http://10.43.50.14:8765/email/sendEmail
  errorEmail:
    addName: SDK for kafka
    reToEmail: cxh_928765@163.com
    subject: failed to send Email
  topic:
    groupName: localGroupHaosc
    topicName: ttcv
server:
  port: 8081
