#logging:
#  config: classpath:logback.xml
# 铁塔kafka框架配置
kafka:
  bootstrap-server: hw_kafka1:19092,hw_kafka2:29092,hw_kafka3:39092
  catch:
    url: http://114.116.254.193:50111/codis/
  consumer:
    auto-commit-interval: 100
    enable-auto-commit: true
    max-poll-records: 8
    session-timeout: 20000
  error:
    url: http://114.116.254.193:38765/email/sendEmail
  errorEmail:
    addName: SDK for kafka
    reToEmail: cxh_928765@163.com
    subject: failed to send Email
  topic:
    groupName: kafka-consumer-Group
    topicName: ttcv,topic_CHNTRMS_IDMM,topic_IDMM_CHNTRMS
  execute-flag: false
server:
  port: 8081
